### ISSUE TITLE
Non-fatal Exception in LinearPercentIndicator

### ISSUE THREAD

**Issue by dodatw** [diegoveloper/flutter_percent_indicator#122]
We face a exception from firebase, we cannot reproduce at ourside.

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at RenderBox.size(RenderBox.java:1962)
       at Element.size(Element.java:3853)
       at _LinearPercentIndicatorState.initState.<fn>.<fn>(<fn>.java:158)
       at State.setState(State.java:1267)
       at _LinearPercentIndicatorState.initState.<fn>(initState.java:157)
       at SchedulerBinding._invokeFrameCallback(SchedulerBinding.java:1144)
       at SchedulerBinding.handleDrawFrame(SchedulerBinding.java:1090)
       at SchedulerBinding._handleDrawFrame(SchedulerBinding.java:998)
```

Is there any idea ?

**Comment by GokayFinfree** [comment]
@dodatw Hi, I got the same error on firebase and have no idea about what is causing this or how to reproduce it. Did u solve it?
