### ISSUE TITLE
Cannot get size in LinearPercentIndicator's initState

### ISSUE THREAD

**Issue by TheVinhLuongFossil** [diegoveloper/flutter_percent_indicator#174]
We are using `flutter_percent_indicator` version `4.2.2`, Flutter SDK version `3.0.5`

Here is our exception stack trace:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at RenderBox.size(box.dart:2001)
       at Element.size(framework.dart:4175)
       at _LinearPercentIndicatorState.initState.<fn>.<fn>(linear_percent_indicator.dart:165)
       at State.setState(framework.dart:1109)
       at _LinearPercentIndicatorState.initState.<fn>(linear_percent_indicator.dart:164)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1146)
       at SchedulerBinding.handleDrawFrame(binding.dart:1091)
       at SchedulerBinding._handleDrawFrame(binding.dart:997)
```
Sadly we cannot reproduce this on our local machine. I think this issue is similar to [this](https://github.com/diegoveloper/flutter_percent_indicator/issues/122) so maybe this is a regression bug?

**Comment by diegoveloper** [comment]
are you sure you are using the latest version? can you check the pubspec.lock file ?

**Comment by TheVinhLuongFossil** [comment]
Yes, I checked the `pubspec.lock` and it is at `4.2.2`. Also, in `pubspec.yaml` we are specifying it as `^4.2.2` so I am certain.

**Comment by diegoveloper** [comment]
hmm I can't reproduce the issue :/

**Comment by noxasch** [comment]
I encounter this issue due to some complex widget tree, currently i make a fork with these changes since i'm haven't be able to identify the actual cause.

somehow the `currentContext?.size?.width` return null in some cases, here is the fix. So far this fix doesn't break any test for `linearprogressindicator` and works fine staging build.

```dart
final RenderBox box =
            _containerKey.currentContext?.findRenderObject() as RenderBox;

        if (box.hasSize) {
          setState(() {
            _containerWidth = _containerKey.currentContext?.size?.width ?? 0.0;
            _containerHeight =
                _containerKey.currentContext?.size?.height ?? 0.0;
            if (_keyIndicator.currentContext != null) {
              _indicatorWidth =
                  _keyIndicator.currentContext?.size?.width ?? 0.0;
              _indicatorHeight =
                  _keyIndicator.currentContext?.size?.height ?? 0.0;
            }
          });
        }
```

**Comment by noxasch** [comment]
maybe related #175 this is cause by complex widget tree which I haven't be able to track the root cause but the patch works for me.

**Comment by mikeesouth** [comment]
I'm also getting this "cannot get size in initState", the stack trace is pretty bad because it comes from Flutter for Web but it's like this:
```
SingleChildRenderObjectElement.get$size 
_LinearPercentIndicatorState_initState__closure0.call$0 
_LinearPercentIndicatorState.setState$1
_LinearPercentIndicatorState_initState_closure.call$1
```

I have a table of data and one cell contains a LinearPercentIndicator. I do not get this all the time but it happens within 5 minutes if I filter and sort the data so that the listview have to rebuild the cells containing LinearPercentIndicator. Before it crashes the percent indicator works really nicely but when I filter the list (add/remove items) - sometimes it crashes with this error. I will try to change `animate: true` to `animate: false` and see if that helps. I'll also test to set shrinkWrap on the listview according to the comment from @noxasch .

I'm using percent_indicator 4.2.2 and Flutter 3.3.3 (stable).

**Comment by phuppert** [comment]
I'm also experiencing this issue. It's occurring very sporadically, but easily often enough to be noticeable. I couldn't reproduce it with a simple toy example today as it only seems to occur in more complex widget trees. In my case, the LinearPercentIndicator is wrapped in a column together with other, more complex content. Multiple of those columns then make up an animated list view in my app which sometimes, on refresh, will cause this error.

I'll try to produce a minimal (non-)working example by occasion. So far, no changes to the LinearPercentIndicator helped.

**Comment by diegoveloper** [comment]
yeah please, try to reproduce it in a minimal sample code in order to fix that , thank you

**Comment by phuppert** [comment]
Using Flutter 3.10.2 and percent_indicator version 4.2.3, I can no longer reproduce this exception. I suspect Flutter 3.10 might have fixed it, but I don't know, honestly. Hooray! 😄 
I'll let you know if it returns in the future, but I think it's gone for good. Thank you for your great work on this package!

**Comment by phuppert** [comment]
Try this:

`import 'dart:async';
import 'package:flutter/material.dart';
import 'package:percent_indicator/linear_percent_indicator.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(AnimatedListExample());
}

class AnimatedListExample extends StatelessWidget {
  AnimatedListExample({
    Key? key,
  }) : super(key: key) {
    // fill list
    () async {
      for (int i = 0; i < 200; i++) {
        await Future.delayed(const Duration(milliseconds: 0));
        _animatedListKey.currentState
            ?.insertItem(0, duration: const Duration(milliseconds: 100));
      }
    }.call();
  }

  final _animatedListKey = GlobalKey<AnimatedListState>();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: AnimatedList(
          key: _animatedListKey,
          itemBuilder: (BuildContext context, int index,
                  Animation<double> animation) =>
              SizeTransition(
                  sizeFactor: animation.drive(Tween(begin: 0.0, end: 1.0)),
                  // the values cannot be the same, there has to be animation
                  child: Column(
                    key: UniqueKey(), // necessary
                    children: [
                      const ListTile(),
                      // other widgets don't seem to cause the same issues
                      LinearPercentIndicator(),
                    ],
                  )),
        ),
      ),
    );
  }
}`

The issue is very difficult to reproduce, but with the above App, I could reproduce it on all devices I've tested (macOS + Web + Android). Also, it only seems to occur when some of the widgets are off-screen. I hope this helps. I swear the above example is the simplest I could do, took me some painstaking 2 hours.

**Comment by Umar1312** [comment]
@diegoveloper  Have you been able to fix this issue? Getting the same on our end

**Comment by victormanuelfrancodev** [comment]
@Umar1312  @phuppert 

The problem is that it tries to draw the component before the render is finished, and to wait for this we can use the LayoutBuilder. With this, it seems that the error is fixed. Please replace line 247 of the class linear_percent_indicator.dart with this. Either way, I've already sent a PR


```
 var containerWidget = LayoutBuilder(
      builder: (context, constraints) {
        _containerWidth = constraints.maxWidth;
        _containerHeight = constraints.maxHeight;
        return Container(
          width: hasSetWidth ? widget.width : double.infinity,
          height: widget.lineHeight,
          padding: widget.padding,
          child: Stack(
            clipBehavior: Clip.none,
            children: [
              CustomPaint(
                key: _containerKey,
                painter: _LinearPainter(
                  isRTL: widget.isRTL,
                  progress: _percent,
                  progressColor: widget.progressColor,
                  linearGradient: widget.linearGradient,
                  backgroundColor: widget.backgroundColor,
                  barRadius: widget.barRadius ??
                      Radius.zero, // If radius is not defined, set it to zero
                  linearGradientBackgroundColor:
                  widget.linearGradientBackgroundColor,
                  maskFilter: widget.maskFilter,
                  clipLinearGradient: widget.clipLinearGradient,
                ),
                child: (widget.center != null)
                    ? Center(child: widget.center)
                    : Container(),
              ),
              if (widget.widgetIndicator != null && _indicatorWidth == 0)
                Opacity(
                  opacity: 0.0,
                  key: _keyIndicator,
                  child: widget.widgetIndicator,
                ),
              if (widget.widgetIndicator != null &&
                  _containerWidth > 0 &&
                  _indicatorWidth > 0)
                Positioned(
                  right: widget.isRTL ? percentPositionedHorizontal : null,
                  left: !widget.isRTL ? percentPositionedHorizontal : null,
                  top: _containerHeight / 2 - _indicatorHeight,
                  child: widget.widgetIndicator!,
                ),
            ],
          ),
        );
      }
    );
```

**Comment by diegoveloper** [comment]
Umar, you don't need to fork, just point the package to his github url and
branch name (in pubspec.yml) , try and see if the bug still exists.

Thanks

**Comment by Umar1312** [comment]
@diegoveloper The PR from @victormanuelfrancodev seems to fix the issue. Can you please merge it if everything else seems fine?

**Comment by AngeloAvv** [comment]
Do you happen to have any updates on this? I'm still often seeing this crash on crashlytics even with version 4.2.4

**Comment by hortigado** [comment]
El problema persiste

**Comment by victormanuelfrancodev** [comment]
@hortigado El problema es el mismo ? 

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at RenderBox.size(box.dart:2001)
       at Element.size(framework.dart:4175)
       at _LinearPercentIndicatorState.initState.<fn>.<fn>(linear_percent_indicator.dart:165)
       at State.setState(framework.dart:1109)
       at _LinearPercentIndicatorState.initState.<fn>(linear_percent_indicator.dart:164)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1146)
       at SchedulerBinding.handleDrawFrame(binding.dart:1091)
       at SchedulerBinding._handleDrawFrame(binding.dart:997)
```

**Comment by hortigado** [comment]
Hi i have it error
@victormanuelfrancodev 

<img width="822" height="156" alt="Image" src="https://github.com/user-attachments/assets/a8d1cf52-e8a7-45e2-b151-aaba926586bd" />

```
Exception caught by rendering library ═════════════════════════════════
The following _TypeError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was:
    LinearPercentIndicator LinearPercentIndicator:file:///Volumes/Externo/Development/Avicultor/lib/ui/postura/postura.dart:411:32

When the exception was thrown, this was the stack:
#0      RenderObject.layout (package:flutter/src/rendering/object.dart:2744:96)
object.dart:2744
#1      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:451:14)
layout_builder.dart:451
#2      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2655:7)
object.dart:2655
#3      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1160:18)
object.dart:1160
#4      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1173:15)
object.dart:1173
#5      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:629:23)
binding.dart:629
#6      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1242:13)
binding.dart:1242
#7      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495:5)
binding.dart:495
#8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1438:15)
binding.dart:1438
#9      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1351:9)
binding.dart:1351
#10     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1060:9)
binding.dart:1060
#11     PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:889:16)
platform_dispatcher.dart:889
#15     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12)
isolate_patch.dart:193
(elided 3 frames from class _Timer and dart:async-patch)

The following RenderObject was being processed when the exception was fired: _RenderLayoutBuilder#48398 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)

```
